import{a,S as m,i as h}from"./assets/vendor-43d6686c.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const p="live_XoqBpjBOBhi4Mxp0uAtNPBYMKHC2s7AGJH7hzvpnhXAnjlaQH6QuAJzfktubymDJ";a.defaults.headers.common["x-api-key"]=p;const l="https://api.thecatapi.com/v1";function u(e){return console.error(e),Promise.reject(e)}function g(){return a.get(`${l}/breeds`).then(e=>e.data).catch(u)}function y(e){return e?a.get(`${l}/images/search?breed_ids=${e}`).then(n=>n.data).catch(u):Promise.resolve([])}const o={breeds:document.querySelector("select.breed-select"),catInfo:document.querySelector("div.cat-info"),loader:document.querySelector("span.loader")};function b(e){return e.map(n=>`<option value="${n.id}">${n.name}</option>`).join("")}function v(e){return`
    <div class="cat-row">
        <img src="${e.url}" alt="${e.breeds[0].name}" width="300px" heigth="200px">
        <div class="cat-text-block">
            <h2>${e.breeds[0].name}</h2>
            <p>${e.breeds[0].description}</p>
            <strong>Temperament:</strong> ${e.breeds[0].temperament}<br>
        </div>
    </div>
    `}function s(e){e?(o.loader.classList.remove("hidden"),o.breeds.classList.add("hidden")):(o.loader.classList.add("hidden"),o.breeds.classList.remove("hidden"))}function f(){h.error({message:"Oops! Something went wrong! Try reloading the page!",position:"topCenter",transitionIn:"fadeInDown"})}function L(e){const n=e.target.value;o.catInfo.innerHTML="",s(!0),y(n).then(i=>{s(!1),o.catInfo.innerHTML=v(i[0])}).catch(i=>{console.error(i),s(!1),f()})}s(!0);g().then(e=>{s(!1),o.breeds.innerHTML=b(e),new m({select:o.breeds,settings:{contentLocation:document.getElementById("local")}})}).catch(e=>{s(!1),console.error(e),f()});o.breeds.addEventListener("change",L);
//# sourceMappingURL=commonHelpers.js.map
